Cloud Events Example
kyma-incubator/examples pull request #20
Opened 2019-07-08 21:49 UTC by montaro

2019-07-08 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/examples?pullRequest=20) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/examples?pullRequest=20) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/examples?pullRequest=20) it.</sub>

2019-07-09 18:09 UTC, sayanh commented on cloud-events-e2e-scenario/README.md
> +package main
This one uses client cert and key
```
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"io/ioutil"
	"log"
	"net/http"
	"time"

	cloudevents "github.com/cloudevents/sdk-go"
	"github.com/google/uuid"
)

func main() {
	event := cloudevents.NewEvent()
	event.Context = cloudevents.EventContextV03{}.AsV03()
	event.SetID(uuid.New().String())
	event.SetType("order.created")
	event.SetSource("external-application")
	event.SetTime(time.Now())
	event.SetExtension("eventtypeversion", "v1")
	event.SetDataContentType("application/json")
	event.SetData(23)

	// Add path to client certificate and key
	cert, err := tls.LoadX509KeyPair("generated.crt", "generated.key")
	if err != nil {
		log.Fatalln("Unable to load cert", err)
	}
	clientCACert, err := ioutil.ReadFile("generated.crt")
	if err != nil {
		log.Fatal("Unable to open cert", err)
	}

	clientCertPool := x509.NewCertPool()
	clientCertPool.AppendCertsFromPEM(clientCACert)

	tlsConfig := &tls.Config{
		Certificates:       []tls.Certificate{cert},
		RootCAs:            clientCertPool,
		InsecureSkipVerify: true,
	}

	tlsConfig.BuildNameToCertificate()

	client := &http.Client{
		Transport: &http.Transport{TLSClientConfig: tlsConfig},
	}
	t, err := cloudevents.NewHTTPTransport(
		cloudevents.WithTarget("https://gateway.kyma.local/sample-external-solution/v2/events"),
		cloudevents.WithStructuredEncoding())

	t.Client = client
	c, err := cloudevents.NewClient(t)
	if err != nil {
		panic("unable to create cloudevent client: " + err.Error())
	}
	_, err = c.Send(context.Background(), event)
	if err != nil {
		panic("failed to send cloudevent: " + err.Error())
	}
}
```

2019-07-11 13:16 UTC, nachtmaar requested changes

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Refer these [instructions](https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/030-inst-local-installation-from-release.md)
Link does not exist

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +Here we will use the [connector service](https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/010-architecture-connector-service.md) to secure the communication.
Cannot find document. 404

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +  > **NOTE** The token is short-lived. So either hurry up or regenrate the token
regenrate => regenerate

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Throughout this workshop we use `workshop` namespace so please create it first.
If this document is aimed at developers, why not simply add a command to create the namespace?

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Under `Integration`, create Application.
According to your style, this should be easier to read: `Integration --> Application --> Create Application`. It helps navigation through the UI.

Proposal: "Create an application at Integration --> Application --> Create Application"

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +  ./one-click-integration.sh -u <paste token here>
Better use `<paste URL>`.I thought I need to paste the token from the URL here. But actually the URL is required.

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +  * Navigate to Administration --> Applications --> sample-external-solution
Should be ``Integration --> Application --> sample-external-solution`

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Navigate to Administration --> Applications --> sample-external-solution
Same here

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* You should see the registered events available.
One needs to switch to `Services` tab first.

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Add to your namespace
You can be more detailed here. E.g. "Add it to your namespace by pressing the `Add once` button".

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Check under `Service Instances` if it appears
in the `Services` tab

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Create the lambda definition in `lambda ui` using [lambda.js](./lambda.js)
I understand that you don't want to tell the user how he has to use the UI to create a lambda or assume the user knows it. However, for a user who doesn't know how to do so, we should at least link to some document/example which explains how to do that.

Maybe change the sentence to `* Create the lambda definition in `lambda ui` using [lambda.js](./lambda.js) in the workshop namespace`

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +  * Add label `app:<name-of-the-lambda>`
The label get's automatically created in the UI. It is `app=<name-of-the-lambda>`

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Select function trigger as event trigger, then choose `order.created`
Press `Select Function trigger` button to create an event trigger, then choose `order.created`

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +
Can you add some log messages to the code ? When I ran it, I got a 404 and nothing else as output.
At least the URL should be printed to stdout.

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/mockbindef.json
> +{
This file is not use or reference. Can it be deleted ?

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/package.json
> +{
I don't think we need this file, do we?

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Refer these [instructions](https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/030-inst-local-installation-from-release.md)
Maybe use the CLI tool for this: `kyma provision minikube` and `kyma install -r master`

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Create the lambda definition in `lambda ui` using [lambda.js](./lambda.js)
Or at least tell the user where to do so.

2019-07-11 13:16 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +import (
The code in  the *.go file should be enough. No need to have it in the Readme too.

2019-07-11 13:21 UTC, montaro commented on cloud-events-e2e-scenario/package.json
> +{
no, we don't 👍

2019-07-11 13:21 UTC, montaro commented on cloud-events-e2e-scenario/mockbindef.json
> +{
Deleted, thanks!

2019-07-11 13:30 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +* Refer these [instructions](https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/030-inst-local-installation-from-release.md)
I will use https://github.com/kyma-project/kyma/blob/master/docs/kyma/04-02-local-installation.md

2019-07-11 13:32 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +Here we will use the [connector service](https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/010-architecture-connector-service.md) to secure the communication.
will fix and use 
https://github.com/kyma-project/kyma/blob/master/docs/application-connector/02-02-connector-service.md

2019-07-11 13:34 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +* Throughout this workshop we use `workshop` namespace so please create it first.
Maybe because it can be created from the UI as well

2019-07-11 14:39 UTC, nachtmaar commented on cloud-events-e2e-scenario/README.md
> +* Throughout this workshop we use `workshop` namespace so please create it first.
Makes sense. Rest of readme uses UI too.

2019-07-11 15:22 UTC, nachtmaar approved these changes
LGTM

2019-07-26 06:37 UTC, bszwarc requested changes
Comments - first round. :)

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +This is an example scenario which demonstrates how Kyma can receive Cloud Events from an external solution. For enabling developers, this scenario is targeted for a **local Kyma installation**.
```suggestion
This is an example scenario which demonstrates how Kyma can receive Cloud Events from an external solution. To make it easier for the developers, this scenario uses a  **local Kyma installation**.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* External solution sends an `order.created` event.
```suggestion
1. The external solution sends an `order.created` Event.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* The event is accepted by Kyma.
```suggestion
2. The Event is accepted by Kyma.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Event triggers the deployed lambda.
```suggestion
* The Event triggers the deployed lambda.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Lambda prints the CE context attributes
```suggestion
* The lambda prints out CE context attributes.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Refer these [instructions](https://github.com/kyma-project/kyma/blob/master/docs/kyma/04-02-local-installation.md)
```suggestion
Use these [instructions](https://github.com/kyma-project/kyma/blob/master/docs/kyma/04-02-local-installation.md) to install and configure Kyma locally.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Create Kyma namespace
```suggestion
### Create a Namespace
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Start Kyma locally
```suggestion
### Install Kyma locally
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Throughout this workshop we use `workshop` namespace so please create it first.
```suggestion
Create a Namespace called `workshop`. You can choose a different name, but remember to use it when calling the commands.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* If you desire to use a different namespace then change each `workshop` here with your desired namespace name.
```suggestion

```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Create Application
```suggestion
### Create Application
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Create an application at `Integration` --> `Application` --> `Create Application`
```suggestion
1. In the Kyma Console, go to **Integration** > **Application** > **Create Application**.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Name it `sample-external-solution`.
```suggestion
2. Enter the Application name: sample-external-solution. 
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Establish secure connection between external solution and Kyma
```suggestion
### Establish secure connection 
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +We will set up the secure connectivity between the mock external solution and the Kyma application `sample-external-solution`.
```suggestion
Use the [connector service](https://github.com/kyma-project/kyma/blob/master/docs/application-connector/02-02-connector-service.md) to establish a secure connection between the mocked external solution and your application.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +Here we will use the [connector service](https://github.com/kyma-project/kyma/blob/master/docs/application-connector/02-02-connector-service.md) to secure the communication.
```suggestion
```
Added to the previous line.

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Clone this [repository](https://github.com/janmedrek/one-click-integration-script).
```suggestion
1. Clone [this repository](https://github.com/janmedrek/one-click-integration-script).
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Copy the token
```suggestion
```
We can remove this and just proceed to the next steps.

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * Navigate to the `Integration --> Applications --> sample-external-solution`
```suggestion
2. In the Kyma Console, navigate to **Integration** > **Applications** > **sample-external-solution**.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * `Connect Application`
```suggestion
3. Click **Connect Application**.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * Copy the token to the clipboard
```suggestion
4. Copy the token.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Use the one-click-generation [helper script](https://github.com/janmedrek/one-click-integration-script) to generate the certificate
```suggestion
5. Use the one-click-generation [helper script](https://github.com/janmedrek/one-click-integration-script) to generate the certificate:
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  This will generate a `generated.pem` file. This contains the signed certificate and key that we will use for subsequent communications.
```suggestion
 This script generates a `generated.pem` file. It contains the signed certificate and key that you will use for subsequent communications.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  > **NOTE** The token is short-lived. So either hurry up or regenerate the token
```suggestion
  > **NOTE** The token expires quickly, so use it right away or generate a new one.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  ```bash
What does this part do?

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Mock External solution
```suggestion
### Mock an external solution
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Calls from external solution to kyma
```suggestion
Use any HTTP client, such as curl or postman, to send a request from the mocked external solution to Kyma.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * Use any http client e.g curl, httpie, postman etc.
```suggestion

```
Combined with the previous one.

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Register events via the metadata api using [register-events.json](./register-events.json)
```suggestion
1. Register Events via the metadata API using [`register-events.json`](./register-events.json):
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Verify
```suggestion

```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * Navigate to Integration --> Applications --> sample-external-solution
```suggestion
To verify the Event flow, navigate to **Integration** > **Applications** > **sample-external-solution**. You can see the registered Events.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * You should see the registered events.
```suggestion

```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Navigate to Integration --> Applications --> sample-external-solution
```suggestion
1. Navigate to **Integration** > **Applications** > **sample-external-solution**
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Create a binding with the Kyma namespace `workshop`.
```suggestion
2. Create a binding with the `workshop` Namespace.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Navigate to Service Catalog for Kyma namespace `workshop`
```suggestion
1. Select the `workshop` Namespace and go to **Service Management** > **Catalog**.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Add events and APIs to the Kyma Namespace
```suggestion
### Add Events and APIs to the Namespace
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +The external solution provides events which is mocked in this example scenario.
```suggestion
This scenario uses a mocked external solution. You can mock the sending of Events using an HTTP client. 
You can also use other mocked or real solutions.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Sending of events is mocked by using a HTTP Client.
```suggestion

```
Combined with the previous one.

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +You can use any other real solutions or mocks that you want to try.
```suggestion

```
Combined with the previous one.

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +
```suggestion
Follow these steps connect an external solution to Kyma:
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Register Events
```suggestion
### Register Events
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Click on `Services`
```suggestion
2. Click **Services** to see the registered Events.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* You should see the registered events available.
```suggestion

```
Combined with the previous one.

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Click on the details
```suggestion
3. Click on the Event entry to reveal details. 
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Add to your namespace by clicking the `Add once` button"
```suggestion
4. Click **Add once** button to add Events to your Namespace.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Check under `Service Instances` --> `Services` tab if it appears
```suggestion
5. Go to **Service Instances** > **Services** tab to see if the Events are available.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Traces are available under <https://jaeger.kyma.local/>
```suggestion
Traces are available under `https://jaeger.kyma.local/`.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Create Lambda
```suggestion
### Create lambda
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Create the lambda definition in lambda ui using [lambda.js](./lambda.js) in the workshop namespace
```suggestion
1. Create the lambda definition in lambda UI using [lambda.js](./lambda.js).
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Press `Select Function trigger` button to create an event trigger, then choose `order.created`
```suggestion
2. Click **Select Function trigger** button to select an Event trigger, then choose **order.created**.
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Publish the event
```suggestion
### Publish the Event
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +# Runtime
```suggestion
## Runtime
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Using the generated certificate from the `./one-click-integration.sh`, send a Cloud Event to the gateway using any HTTP client e.g curl, httpie, postman etc. or a CloudEvents SDK, check this exampl
```suggestion
Use the certificate generated by the `./one-click-integration.sh` script to send a Cloud Event to the gateway using any HTTP client, such as curl, httpie, or postman. You can also use CloudEvents SDK. For details, see [this example](./example.go)
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +# Verification
```suggestion
## Verification
```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* **Lambda was triggered**
```suggestion

```

2019-07-26 06:37 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +  * Inspect the pod logs for lambda in `workshop` namespace
```suggestion
To check if the lambda function was triggered properly, inspect the Pod logs in the `workshop` Namespace:
```

2019-07-26 06:38 UTC, bszwarc requested changes
Comments - first round. :)

2019-07-29 10:47 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +  ```bash
@bszwarc Capture the node port to use it in the following steps

2019-07-29 10:56 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +* Create the lambda definition in lambda ui using [lambda.js](./lambda.js) in the workshop namespace
@bszwarc why deleting the namespace?

2019-07-29 11:04 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +  ```bash
@bszwarc You're right, this will not be used here! will remove it.

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +# Description
```suggestion
# Receive Events from an external solution
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* The Event triggers the deployed lambda.
```suggestion
3. The Event triggers the deployed lambda.
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* The lambda prints out CE context attributes.
```suggestion
4. The lambda prints out CE context attributes.
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +# Set up
```suggestion
## Prerequisites
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +
Remove the empty lines.

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +
```suggestion
## Installation
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +* Create the lambda definition in lambda ui using [lambda.js](./lambda.js) in the workshop namespace
I assumed the user knows that he is doing everything using this namespace. But it may stay to make it more explicit.

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +# Tracing
```suggestion

```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +Traces are available under `https://jaeger.kyma.local/`.
```suggestion
You can also find traces under `https://jaeger.kyma.local/`.
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +## Bind Application
```suggestion
### Bind Application
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +
Remove this line

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +This is an example scenario which demonstrates how Kyma can receive Cloud Events from an external solution. To make it easier for the developers, this scenario uses a  **local Kyma installation**.
```suggestion
This is an example scenario which demonstrates how Kyma can receive Cloud Events from an external solution. To make things easier, this scenario uses a  **local Kyma installation**.
```

2019-08-05 12:58 UTC, bszwarc commented on cloud-events-e2e-scenario/README.md
> +Create a Namespace called `workshop`. You can choose a different name, but remember to use it when calling the commands.
```suggestion
Create a Namespace called `workshop`. You can choose a different name, but remember to use it in the commands.
```

2019-08-05 13:14 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +# Description
@bszwarc We should emphasize that it's [Cloud Events](https://cloudevents.io/)

2019-08-05 13:30 UTC, montaro commented on cloud-events-e2e-scenario/README.md
> +# Description
```suggestion
# Receive Cloud Events from an external solution
```

2019-08-05 16:02 UTC, bszwarc approved these changes

2019-08-05 16:10 UTC, merged